modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="project"
version="Alpha 1.0.0"
displayName="project"
credits="Créer par sampa17 ."
displayURL="https://github.com/sampa17/underworld"
authors="sampa, cornysneeze"
description='''
Ce mod rajoute un monde en dessous de la surface , sous la Bedrock , l'Underworld .
'''

[[dependencies.project]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



